### ISSUE TITLE
enhancement: modbus registers for goodWe

### ISSUE THREAD

**Issue by hawa-lc4** [steff393/wbecModbus#1]
Hallo,

ich habe einen goodWe GW10K-ET Hybrid-Inverter in Betrieb und möchte hier für die ET/EH/BH/BT Serien die Einträge in der .ini Datei teilen.
Die Registeradressen habe ich mit der goodWe Modbus Liste abgeglichen.
Die Power Register liefern den Datenwert signed integer und werden meist mit -1 multipliziert, dann bedeutet "positiv = Bezug/Import/Ladung" und "negativ = Einspeisung/Export/Entladung":

[goodWe] # "cfgInverterType":9
Port  = 502
Addr  = 247
36008 = 1 # MeterTotalActivepower  * -1
36005 = 3 # MeterActivepowerR, S, T  * -1
36010 = 3 # MeterPF_R, S, T  / 1000
36014 = 1 # MeterFrequence  / 100
35105 = 2 # PV1 Power  * -1
35109 = 2 # PV2 Power  * -1
35113 = 2 # PV3 Power  * -1
35117 = 2 # PV4 Power  * -1
35191 = 2 # Total PV Energy  * 100
37007 = 1 # Batt SOC
37008 = 1 # Batt BMS SOH
35206 = 2 # Batt Charge energy  * 100
35209 = 2 # Batt Discharge energy  * 100
35183 = 1 # Batt Power  * -1

hth.

**Comment by steff393** [comment]
Hi, den hab ich auch :-)
Allerdings geht das über Modbus-TCP nur mit Hilfe des Wifi/LAN-Kit v2, oder? Direkt über WLAN geht's bei mir nicht. 
Lese ihn aktuell über Modbus-RTU aus.

Danke, hab's eingebaut.

**Comment by hawa-lc4** [comment]
Hi, das mit Modbus-TCP stimmt leider für den reinen WLAN-Stick. Bei dem hat goodwe den TCP Port 502 extra gesperrt (Sauerei! :); der UDP Port 502 soll angeblich offen sein, eine TCP-UDP bridge zu bauen war mir aber zu aufwändig.
Richtig ist auch das das WiFi/LAN Kit diesen Port offen hat aber nur beim Anschluß über Kabel-LAN.
Ich lese den auch direkt über die RS485 Schnittstelle mit einer Modbus RTU zu TCP Bridge basierend auf Tasmota aus.

Und vielen Dank für die Arbeit du dir hier mit diesem Tools gemacht hast und machst!
